app/routes/index.py
from flask import Blueprint, render_template, redirect

# -------------------------

index_bp = Blueprint('index', __name__)

# -------------------------

@index_bp.route('/')
def home():
    return render_template('pages/home.html')

@index_bp.route('/about.html')
def about():
    return render_template('about.html')

@index_bp.route('/projects.html')
def projects():
    return render_template('about.html')

@index_bp.route('/contact.html')
def contact():
    return render_template('contact.html')

@index_bp.route('/instagram')
def instagram():
    return redirect('https://www.instagram.com/robertovicario__')

app/templates/includes/header.html
<!-- Header -->
<header class="navbar navbar-top navbar-expand navbar-dark navbar-fixed">
    <div class="container justify-content-between">
        <a class="navbar-brand" href="/">
            <img width="64" src="{{ url_for('static', filename='/img/Logo-2.svg') }}" alt="">
        </a>
        <a class="navbar-toggle" href="#menu" data-fancybox data-base-class="fancybox-navbar" data-keyboard="false" data-auto-focus="false" data-touch="false" data-close-existing="true" data-small-btn="false" data-toolbar="false">
            <span></span>
            <span></span>
            <span></span>
        </a>
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a href="{{ url_for('index.home') }}" class="nav-link">home</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('index.about') }}" class="nav-link">about</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('index.projects') }}" class="nav-link">projects</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('index.contact') }}" class="nav-link">contact</a>
            </li>
        </ul>
        <ul class="nav nav-gap-sm navbar-nav nav-social align-items-center">
            <li class="nav-item">
                <a href="{{ url_for('index.instagram') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                    <i class="fa-brands fa-instagram" style="font-size: 24px;"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('index.instagram') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                    <i class="fa-brands fa-linkedin-in" style="font-size: 24px;"></i>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('index.instagram') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                    <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                </a>
            </li>
        </ul>
    </div>
</header>
<div class="navbar navbar-mobile navbar-mobile-style-2 navbar-dark" id="menu">
    <div class="shape justify-content-end">
        <svg data-rellax-speed="0" width="544" height="362" viewBox="0 0 544 362" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="320.5" cy="41.5" r="320.5" fill=" #202020"/>
        </svg>
    </div>
    <div class="navbar-head">
        <div class="container justify-content-between">
            <a class="navbar-brand" href="index.html">
                <img width="107" src="{{ url_for('static', filename='/images/logo-white.svg') }}" alt="">
            </a>
            <a class="navbar-toggle" href="#" data-fancybox-close>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </div>
    </div>
    <div class="container">
        <div class="row gh-1 justify-content-center">
            <div class="col-12 col-md-7 col-lg-5 col-xl-4">
                <div class="navbar-body">
                    <ul class="nav navbar-nav navbar-nav-collapse">
                        <li class="nav-item active">
                            <a href="{{ url_for('index.home') }}" class="nav-link">
                                <span class="nav-link-name">home</span>
                                <svg class="collapse-icon" width="7" height="12" viewBox="0 0 7 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 11L6 6L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('index.about') }}" class="nav-link">
                                <span class="nav-link-name">about</span>
                                <svg class="collapse-icon" width="7" height="12" viewBox="0 0 7 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 11L6 6L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('index.projects') }}" class="nav-link">
                                <span class="nav-link-name">projects</span>
                                <svg class="collapse-icon" width="7" height="12" viewBox="0 0 7 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 11L6 6L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('index.contact') }}" class="nav-link">
                                <span class="nav-link-name">contact</span>
                                <svg class="collapse-icon" width="7" height="12" viewBox="0 0 7 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M1 11L6 6L1 1" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-1 d-none d-md-block"></div>
            <div class="col-12 col-md-4 col-lg-4 col-xl-3">
                <div class="navbar-footer">
                    <div class="mb-60 text-white">
                        <p class="lead mb-17 fw-medium">Email:</p>
                        <ul class="list-group borderless font-size-17">
                            <li class="list-group-item"><a href="{{ url_for('index.home') }}" class="text-decoration-none text-white">robertovicario.com@gmail.com</a></li>
                        </ul>
                    </div>
                    <div class="mb-60 text-white">
                        <p class="lead mb-17 fw-medium">Position:</p>
                        <ul class="list-group borderless font-size-17">
                            <li class="list-group-item">Como, Italy</li>
                            <li class="list-group-item">Milan, Italy</li>
                            <li class="list-group-item">Lugano, Switzerland</li>
                        </ul>
                    </div>
                    <ul class="nav nav-gap-sm navbar-nav nav-social align-items-center mt-n10">
                        <li class="nav-item">
                            <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                <i class="fa-brands fa-instagram" style="font-size: 24px;"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                <i class="fa-brands fa-linkedin-in" style="font-size: 24px;"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/page.html
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    
    <!-- Theme -->
    <title>Roberto Vicario | {{ theme_title }}</title>
    <meta name="theme-color" content="#000000"/>

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicons/favicon-16x16.png') }}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicons/favicon-32x32.png') }}"/>
    <link rel="apple-touch-icon" type="image/png" sizes="180x180" href="{{ url_for('static', filename='img/favicons/apple-touch-icon.png') }}"/>
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='img/favicons/android-chrome-192x192.png') }}"/>
    <link rel="icon" type="image/png" sizes="512x512" href="{{ url_for('static', filename='img/favicons/android-chrome-512x512.png') }}"/>

    <!-- SEO -->
    <meta name="description" content="Discover the work and projects of Roberto Vicario, a software engineer specializing in web development, cloud computing, and AI. Explore his portfolio and get in touch today.">
    <meta name="keywords" content="Roberto Vicario, software engineer, web development, cloud computing, AI, portfolio">
    <meta name="robots" content="index, follow">

    <!-- Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Syncopate:wght@400;700&display=swap" rel="stylesheet">

    <!-- Libraries -->
    <!-- TODO: external=_True -->
    <link rel="stylesheet" href="{{ url_for('static', filename='/vendor/swiper/dist/css/swiper.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/vendor/fancybox/dist/jquery.fancybox.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/themebau.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/custom.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- Styles -->
    {% block styles %}{% endblock %}
</head>

<body class="bg-dark">

    <!-- Jinja :: Header -->
    {% include 'includes/header.html' %}

    <!-- Jinja :: Content -->
    {% block content %}{% endblock %}

    <!-- Libraries -->
    <!-- TODO: external=_True -->
    <script src="{{ url_for('static', filename='/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/object-fit-images/dist/ofi.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/swiper/dist/js/swiper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/animejs/lib/anime.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/rellax/rellax.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/jquery-countdown/dist/jquery.countdown.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/moment/min/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/moment-timezone/builds/moment-timezone-with-data.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/isotope-layout/dist/isotope.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/isotope-packery/packery-mode.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/jarallax/dist/jarallax.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/jarallax/dist/jarallax-video.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/vendor/fancybox/dist/jquery.fancybox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='/js/themebau.min.js') }}"></script>

    <!-- Scripts -->
    {% block scripts %}{% endblock %}
</body>

</html>

app/templates/pages/home.html
<!-- Jinja :: Template -->
{% extends 'page.html' %}

<!-- Jinja :: Theme -->
{% set theme_title = 'Software Engineer' %}

<!-- Jinja :: Styles -->
{% block styles %}{% endblock %}

<!-- Jinja :: Content -->
{% block content %}
<div class="content-wrap">
    <div class="swiper text-white swiper-fullscreen-vertical" data-swiper-slides="1" data-swiper-speed="600" data-swiper-vertical="true">
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="card-wrapper h-100">
                        <a class="card card-fullscreen text-white" href="about-me.html" data-cursor-style="cursor-circle" data-cursor-text="view">
                            <span class="card-img">
                                <img src="{{ url_for('static', filename='/img/home/1.png') }}" alt="">
                                <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                            </span>
                            <span class="card-img-overlay container">
                                <h2 class="card-title h1 mb-0">
                                    <span class="card-title-decoration"></span>
                                    <span>Hi, I'm Roberto 👋🏻</span>
                                    <br><br>
                                    <h5 class="mb-0 text-white">Software Engineer<br>@ Motus ml</h5>
                                </h2>
                                <span class="btn btn-clean">
                                    <span class="me-3">about me</span>
                                    <i class="bi bi-arrow-right"></i>
                                </span>
                            </span>
                        </a>
                        <div class="card-social-container container">
                            <ul class="card-social nav nav-gap-md align-items-center flex-column text-white">
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-instagram" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-linkedin-in" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="card-wrapper h-100">
                        <a class="card card-fullscreen text-white" href="portfolio.html" data-cursor-style="cursor-circle" data-cursor-text="view">
                            <span class="card-img">
                                <img src="{{ url_for('static', filename='/img/home/2.png') }}" alt="">
                                <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                            </span>
                            <span class="card-img-overlay container">
                                <h2 class="card-title h1 mb-0">
                                    <span class="card-title-decoration"></span>
                                    <span>Explore my portfolio 🤟🏻</span>
                                </h2>
                                <span class="btn btn-clean">
                                    <span>learn more</span>
                                    <svg class="icon-arrow icon-arrow-right" width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
                                        <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round'/>
                                        <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round'/>
                                    </svg>
                                </span>
                            </span>
                        </a>
                        <div class="card-social-container container">
                            <ul class="card-social nav nav-gap-md align-items-center flex-column text-white">
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-instagram" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-linkedin-in" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="card-wrapper h-100">
                        <a class="card card-fullscreen text-white" href="contact-me.html" data-cursor-style="cursor-circle" data-cursor-text="view">
                            <span class="card-img">
                                <img src="{{ url_for('static', filename='/img/home/3.png') }}" alt="">
                                <span class="background-color" style="background-color: rgba(14, 14, 14, .2);"></span>
                            </span>
                            <span class="card-img-overlay container">
                                <h2 class="card-title h1 mb-0"><span class="card-title-decoration"></span>Let's get in touch 🤙🏻</h2>
                                <span class="btn btn-clean">
                                    <span>contact me</span>
                                    <svg class="icon-arrow icon-arrow-right" width='26' height='11' viewBox='0 0 26 11' fill='none' xmlns='http://www.w3.org/2000/svg'>
                                        <path d='M20.5 1L25 5.5L20.5 10' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round'/>
                                        <path d='M7 5.5H25' stroke='currentColor' stroke-width='1.3' stroke-linecap='round' stroke-linejoin='round'/>
                                    </svg>
                                </span>
                            </span>
                        </a>
                        <div class="card-social-container container">
                            <ul class="card-social nav nav-gap-md align-items-center flex-column text-white">
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-instagram" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-linkedin-in" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ url_for('index.home') }}" target="_blank" rel="noopener noreferrer" class="nav-link">
                                        <i class="fa-brands fa-github" style="font-size: 24px;"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-pagination-wrapper container justify-content-end">
            <div class="swiper-pagination"></div>
        </div>
    </div>
</div>
{% endblock %}

<!-- Jinja :: Scripts -->
{% block scripts %}{% endblock %}